### ISSUE TITLE
Create column on conference model to indicate activity

### ISSUE THREAD

**Issue by warrenshen** [calblueprint/edge-yl#1192]

**Comment by maxwolffe** [comment]
@warrenshen 

Can you explain this a little bit? What's the intention behind having an active conference? Can two conferences be active (say if they are happening at the same time)?

**Comment by warrenshen** [comment]
My current thinking right now is we need a way to know which conference to assign `Student`s to when they complete their registration. I must admit I didn't think of having two conferences at the same time - but would it be reasonable to assume that registration for conference can only happen for one conference at a time?

**Comment by maxwolffe** [comment]
Presumably registration happens over a period of several months (registration being students filling out their forms, I presume?). Instead of having a global 'active', how about attaching the conference id to the form, and specifying the conference_id when the email is sent out? Not sure if that makes sense, but maybe we can talk about it tomorrow at work session?

**Comment by warrenshen** [comment]
I like the direction your idea is going - sounds good!
